"""phase 5 order fulfillment and delivery

Revision ID: 316505afe081
Revises: 831f90de6582
Create Date: 2026-10-04 10:32:00.041968

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "316505afe081"
down_revision = "831f90de6582"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("destination_county", sa.String(length=40), nullable=True),
        sa.Column("location_name", sa.String(length=120), nullable=True),
        sa.Column("address_text", sa.String(length=500), nullable=True),
        sa.Column("recipient_name", sa.String(length=120), nullable=True),
        sa.Column("recipient_phone", sa.String(length=16), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "method != 'DELIVERY' OR (destination_county IS NOT NULL "
            "AND location_name IS NOT NULL AND address_text IS NOT NULL "
            "AND recipient_name IS NOT NULL AND recipient_phone IS NOT NULL)",
            name="ck_deliveries_destination_required",
        ),
        sa.CheckConstraint("method IN ('PICKUP','DELIVERY')", name="ck_deliveries_method"),
        sa.CheckConstraint(
            "status IN ('PENDING','PREPARING','READY','IN_TRANSIT','DELIVERED','CANCELLED')",
            name="ck_deliveries_status",
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    with op.batch_alter_table("order_status_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("previous_status", sa.String(length=20), nullable=True))
        batch_op.alter_column("actor_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "status", existing_type=sa.String(length=12), type_=sa.String(length=20), nullable=False
        )
        batch_op.create_check_constraint(
            "ck_order_status_history_status",
            "status IN ('PENDING','CONFIRMED','PAID','PROCESSING','READY_FOR_PICKUP',"
            "'IN_TRANSIT','DELIVERED','COMPLETED','CANCELLED','DISPUTED')",
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("left_seller_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_constraint("ck_orders_status", type_="check")
        batch_op.alter_column(
            "status", existing_type=sa.String(length=12), type_=sa.String(length=20), nullable=False
        )
        batch_op.create_check_constraint(
            "ck_orders_status",
            "status IN ('PENDING','CONFIRMED','PAID','PROCESSING','READY_FOR_PICKUP',"
            "'IN_TRANSIT','DELIVERED','COMPLETED','CANCELLED','DISPUTED')",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_constraint("ck_orders_status", type_="check")
        batch_op.alter_column(
            "status", existing_type=sa.String(length=20), type_=sa.String(length=12), nullable=False
        )
        batch_op.create_check_constraint(
            "ck_orders_status", "status IN ('CONFIRMED','CANCELLED','COMPLETED')"
        )
        batch_op.drop_column("cancelled_at")
        batch_op.drop_column("completed_at")
        batch_op.drop_column("delivered_at")
        batch_op.drop_column("left_seller_at")

    with op.batch_alter_table("order_status_history", schema=None) as batch_op:
        batch_op.drop_constraint("ck_order_status_history_status", type_="check")
        batch_op.alter_column(
            "status", existing_type=sa.String(length=20), type_=sa.String(length=12), nullable=False
        )
        batch_op.alter_column("actor_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("previous_status")

    op.drop_table("deliveries")
    # ### end Alembic commands ###
