"""create authentication models

Revision ID: 3d5f4d1f075b
Revises:
Create Date: 2026-10-04 02:43:31.960096

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3d5f4d1f075b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=True),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_suspended", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "role IS NULL OR role IN ('FARMER', 'BUYER', 'ADMIN')", name="ck_users_role"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_phone"), ["phone"], unique=True)

    op.create_table(
        "otp_challenges",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("code_hmac", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("request_ip", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("otp_challenges", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_otp_challenges_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_otp_challenges_expires_at"), ["expires_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_otp_challenges_phone"), ["phone"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_otp_challenges_request_ip"), ["request_ip"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_otp_challenges_user_id"), ["user_id"], unique=False)

    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("rating_avg", sa.Float(), nullable=True),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("completed_orders_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profiles")
    with op.batch_alter_table("otp_challenges", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_otp_challenges_user_id"))
        batch_op.drop_index(batch_op.f("ix_otp_challenges_request_ip"))
        batch_op.drop_index(batch_op.f("ix_otp_challenges_phone"))
        batch_op.drop_index(batch_op.f("ix_otp_challenges_expires_at"))
        batch_op.drop_index(batch_op.f("ix_otp_challenges_created_at"))

    op.drop_table("otp_challenges")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_phone"))

    op.drop_table("users")
    # ### end Alembic commands ###
