"""phase-3 marketplace and listings

Revision ID: 4f0201494097
Revises: f6495a62d8ec
Create Date: 2026-10-04 03:50:38.626096

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4f0201494097"
down_revision = "f6495a62d8ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=90), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(name) BETWEEN 2 AND 80", name="ck_categories_name_length"),
        sa.CheckConstraint("length(slug) BETWEEN 2 AND 90", name="ck_categories_slug_length"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("seller_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=8), nullable=False),
        sa.Column("grade", sa.String(length=12), nullable=False),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("moderation_status", sa.String(length=16), nullable=False),
        sa.Column("county", sa.String(length=40), nullable=False),
        sa.Column("location_name", sa.String(length=120), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(title) BETWEEN 3 AND 120", name="ck_listings_title_length"),
        sa.CheckConstraint(
            "length(trim(description)) BETWEEN 1 AND 5000",
            name="ck_listings_description_length",
        ),
        sa.CheckConstraint("grade IN ('A', 'B', 'C', 'UNGRADED')", name="ck_listings_grade"),
        sa.CheckConstraint(
            "moderation_status IN ('APPROVED', 'FLAGGED', 'REMOVED')",
            name="ck_listings_moderation_status",
        ),
        sa.CheckConstraint(
            "status IN ('AVAILABLE', 'UNAVAILABLE', 'SOLD')", name="ck_listings_status"
        ),
        sa.CheckConstraint(
            "unit IN ('KG', 'BAG', 'TONNE', 'CRATE', 'PIECE', 'LITRE')", name="ck_listings_unit"
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR latitude BETWEEN -90 AND 90", name="ck_listings_latitude"
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180", name="ck_listings_longitude"
        ),
        sa.CheckConstraint("price_minor > 0", name="ck_listings_price_positive"),
        sa.CheckConstraint("quantity >= 0", name="ck_listings_quantity_nonnegative"),
        sa.CheckConstraint(
            "status != 'AVAILABLE' OR quantity > 0",
            name="ck_listings_available_quantity_positive",
        ),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["seller_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_listings_public_category",
            ["moderation_status", "status", "category_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_listings_public_county", ["moderation_status", "status", "county"], unique=False
        )
        batch_op.create_index(
            "ix_listings_public_created",
            ["moderation_status", "status", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_listings_public_price", ["moderation_status", "status", "price_minor"], unique=False
        )
        batch_op.create_index(
            "ix_listings_seller_created", ["seller_id", "created_at"], unique=False
        )

    op.create_table(
        "listing_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=40), nullable=False),
        sa.Column("original_filename", sa.String(length=160), nullable=True),
        sa.Column("mime_type", sa.String(length=32), nullable=False),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("filename"),
    )
    with op.batch_alter_table("listing_images", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_listing_images_listing_id"), ["listing_id"], unique=False
        )
        batch_op.create_index(
            "uq_listing_images_one_primary",
            ["listing_id"],
            unique=True,
            sqlite_where=sa.text("is_primary = 1"),
            postgresql_where=sa.text("is_primary = true"),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("listing_images", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_listing_images_one_primary",
            sqlite_where=sa.text("is_primary = 1"),
            postgresql_where=sa.text("is_primary = true"),
        )
        batch_op.drop_index(batch_op.f("ix_listing_images_listing_id"))

    op.drop_table("listing_images")
    with op.batch_alter_table("listings", schema=None) as batch_op:
        batch_op.drop_index("ix_listings_seller_created")
        batch_op.drop_index("ix_listings_public_price")
        batch_op.drop_index("ix_listings_public_created")
        batch_op.drop_index("ix_listings_public_county")
        batch_op.drop_index("ix_listings_public_category")

    op.drop_table("listings")
    op.drop_table("categories")
    # ### end Alembic commands ###
