"""phase-6 payment records

Revision ID: 907c8b4797dc
Revises: 316505afe081
Create Date: 2026-10-04 11:20:23.356191

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "907c8b4797dc"
down_revision = "316505afe081"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=12), nullable=False),
        sa.Column("provider_reference", sa.String(length=255), nullable=True),
        sa.Column("provider_resource_id", sa.String(length=255), nullable=True),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=18), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("failure_code", sa.String(length=80), nullable=True),
        sa.Column("refund_reference", sa.String(length=255), nullable=True),
        sa.Column("refund_pending", sa.Boolean(), nullable=False),
        sa.Column("initiated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("currency = 'KES'", name="ck_payments_currency_kes"),
        sa.CheckConstraint("provider IN ('MOCK','MPESA','STRIPE')", name="ck_payments_provider"),
        sa.CheckConstraint(
            "status IN ('INITIATED','PENDING','SUCCEEDED','FAILED','EXPIRED','REFUNDED')",
            name="ck_payments_status",
        ),
        sa.CheckConstraint("amount_minor > 0", name="ck_payments_amount_positive"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        sa.UniqueConstraint(
            "provider", "provider_reference", name="uq_payments_provider_reference"
        ),
    )
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.create_index("ix_payments_order_created", ["order_id", "created_at"], unique=False)
        batch_op.create_index(
            "uq_payments_one_active_per_order",
            ["order_id"],
            unique=True,
            sqlite_where=sa.text("status IN ('INITIATED','PENDING')"),
            postgresql_where=sa.text("status IN ('INITIATED','PENDING')"),
        )
        batch_op.create_index(
            "uq_payments_one_success_per_order",
            ["order_id"],
            unique=True,
            sqlite_where=sa.text("status IN ('SUCCEEDED','REFUNDED')"),
            postgresql_where=sa.text("status IN ('SUCCEEDED','REFUNDED')"),
        )

    op.create_table(
        "payment_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("provider", sa.String(length=12), nullable=False),
        sa.Column("provider_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_status", sa.String(length=20), nullable=False),
        sa.Column("result_message", sa.String(length=160), nullable=True),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "processing_status IN ('PROCESSED','DUPLICATE','REJECTED','ACTION_REQUIRED')",
            name="ck_payment_events_status",
        ),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_event_id", name="uq_payment_events_provider_event"
        ),
    )
    with op.batch_alter_table("payment_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_payment_events_payment_received", ["payment_id", "received_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_events", schema=None) as batch_op:
        batch_op.drop_index("ix_payment_events_payment_received")

    op.drop_table("payment_events")
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_payments_one_success_per_order",
            sqlite_where=sa.text("status IN ('SUCCEEDED','REFUNDED')"),
            postgresql_where=sa.text("status IN ('SUCCEEDED','REFUNDED')"),
        )
        batch_op.drop_index(
            "uq_payments_one_active_per_order",
            sqlite_where=sa.text("status IN ('INITIATED','PENDING')"),
            postgresql_where=sa.text("status IN ('INITIATED','PENDING')"),
        )
        batch_op.drop_index("ix_payments_order_created")

    op.drop_table("payments")
    # ### end Alembic commands ###
