"""phase 9 admin audit and notifications

Revision ID: a5699c311989
Revises: dc89ed65df7e
Create Date: 2026-10-04 16:35:18.149658

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5699c311989"
down_revision = "dc89ed65df7e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=40), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "action IN ('USER_SUSPENDED','USER_REACTIVATED','LISTING_FLAGGED',"
            "'LISTING_APPROVED','LISTING_REMOVED','DISPUTE_MOVED_TO_REVIEW',"
            "'DISPUTE_RESOLVED_FOR_BUYER','DISPUTE_RESOLVED_FOR_SELLER')",
            name="ck_audit_logs_action",
        ),
        sa.CheckConstraint(
            "target_type IN ('user','listing','dispute')", name="ck_audit_logs_target"
        ),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_logs_action_created", ["action", "created_at"], unique=False
        )
        batch_op.create_index("ix_audit_logs_created", ["created_at", "id"], unique=False)

    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_constraint("ck_notifications_type", type_="check")
        batch_op.create_check_constraint(
            "ck_notifications_type",
            "notification_type IN ("
            "'MESSAGE_RECEIVED','OFFER_RECEIVED','OFFER_ACCEPTED','OFFER_REJECTED',"
            "'OFFER_COUNTERED','ORDER_CONFIRMED','ORDER_CANCELLED','ORDER_PROCESSING',"
            "'PAYMENT_SUCCEEDED','PAYMENT_FAILED','ORDER_READY_FOR_PICKUP','ORDER_IN_TRANSIT',"
            "'ORDER_DELIVERED','ORDER_COMPLETED','REVIEW_RECEIVED','DISPUTE_OPENED',"
            "'DISPUTE_UNDER_REVIEW','DISPUTE_RESOLVED_FOR_BUYER',"
            "'DISPUTE_RESOLVED_FOR_SELLER','REFUND_SUCCEEDED','REFUND_FAILED',"
            "'LISTING_FLAGGED','LISTING_REMOVED','ACCOUNT_SUSPENDED','ACCOUNT_REACTIVATED')",
        )

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_constraint("ck_notifications_type", type_="check")
        batch_op.create_check_constraint(
            "ck_notifications_type",
            "notification_type IN ("
            "'MESSAGE_RECEIVED','OFFER_RECEIVED','OFFER_ACCEPTED','OFFER_REJECTED',"
            "'OFFER_COUNTERED','ORDER_CONFIRMED','ORDER_CANCELLED','ORDER_PROCESSING',"
            "'PAYMENT_SUCCEEDED','PAYMENT_FAILED','ORDER_READY_FOR_PICKUP','ORDER_IN_TRANSIT',"
            "'ORDER_DELIVERED','ORDER_COMPLETED','REVIEW_RECEIVED','DISPUTE_OPENED',"
            "'DISPUTE_UNDER_REVIEW','DISPUTE_RESOLVED_FOR_BUYER',"
            "'DISPUTE_RESOLVED_FOR_SELLER','REFUND_SUCCEEDED','REFUND_FAILED')",
        )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_logs_created")
        batch_op.drop_index("ix_audit_logs_action_created")

    op.drop_table("audit_logs")
    # ### end Alembic commands ###
