"""add persisted notifications

Revision ID: dc89ed65df7e
Revises: ea992dee83a7
Create Date: 2026-10-04 15:58:16.380101

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dc89ed65df7e"
down_revision = "ea992dee83a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("notification_type", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=True),
        sa.Column("target_id", sa.Integer(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(target_type IS NULL AND target_id IS NULL) OR "
            "(target_type IN ('conversation','order','listing','seller') AND target_id > 0)",
            name="ck_notifications_target",
        ),
        sa.CheckConstraint(
            "(is_read = 0 AND read_at IS NULL) OR (is_read = 1 AND read_at IS NOT NULL)",
            name="ck_notifications_read_timestamp",
        ),
        sa.CheckConstraint(
            "notification_type IN ("
            "'MESSAGE_RECEIVED','OFFER_RECEIVED','OFFER_ACCEPTED','OFFER_REJECTED',"
            "'OFFER_COUNTERED','ORDER_CONFIRMED','ORDER_CANCELLED','ORDER_PROCESSING',"
            "'PAYMENT_SUCCEEDED','PAYMENT_FAILED','ORDER_READY_FOR_PICKUP','ORDER_IN_TRANSIT',"
            "'ORDER_DELIVERED','ORDER_COMPLETED','REVIEW_RECEIVED','DISPUTE_OPENED',"
            "'DISPUTE_UNDER_REVIEW','DISPUTE_RESOLVED_FOR_BUYER',"
            "'DISPUTE_RESOLVED_FOR_SELLER','REFUND_SUCCEEDED','REFUND_FAILED')",
            name="ck_notifications_type",
        ),
        sa.CheckConstraint("length(trim(body)) BETWEEN 1 AND 500", name="ck_notifications_body"),
        sa.CheckConstraint("length(trim(title)) BETWEEN 1 AND 120", name="ck_notifications_title"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            "ix_notifications_user_created", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_notifications_user_read_created",
            ["user_id", "is_read", "created_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index("ix_notifications_user_read_created")
        batch_op.drop_index(batch_op.f("ix_notifications_user_id"))
        batch_op.drop_index("ix_notifications_user_created")

    op.drop_table("notifications")
    # ### end Alembic commands ###
