"""add reviews and disputes

Revision ID: ea992dee83a7
Revises: 907c8b4797dc
Create Date: 2026-10-04 15:23:36.053993

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ea992dee83a7"
down_revision = "907c8b4797dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "disputes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("opened_by", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("resolution_note", sa.String(length=2000), nullable=True),
        sa.Column("resolution_target", sa.String(length=24), nullable=True),
        sa.Column("resolution_pending", sa.Boolean(), nullable=False),
        sa.Column("resolution_requested_by", sa.Integer(), nullable=True),
        sa.Column("resolved_by", sa.Integer(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "reason IN ('ITEM_NOT_RECEIVED','ITEM_NOT_AS_DESCRIBED','QUALITY_ISSUE',"
            "'QUANTITY_ISSUE','PAYMENT_ISSUE','DELIVERY_ISSUE','OTHER')",
            name="ck_disputes_reason",
        ),
        sa.CheckConstraint(
            "resolution_target IS NULL OR resolution_target IN "
            "('RESOLVED_FOR_BUYER','RESOLVED_FOR_SELLER')",
            name="ck_disputes_resolution_target",
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','UNDER_REVIEW','RESOLVED_FOR_BUYER','RESOLVED_FOR_SELLER')",
            name="ck_disputes_status",
        ),
        sa.CheckConstraint(
            "length(trim(description)) BETWEEN 1 AND 4000", name="ck_disputes_description_length"
        ),
        sa.ForeignKeyConstraint(["opened_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["resolution_requested_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", name="uq_disputes_one_per_order"),
    )
    with op.batch_alter_table("disputes", schema=None) as batch_op:
        batch_op.create_index("ix_disputes_status_opened", ["status", "opened_at"], unique=False)

    op.create_table(
        "reviews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("reviewer_id", sa.Integer(), nullable=False),
        sa.Column("seller_id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(trim(body)) BETWEEN 1 AND 2000", name="ck_reviews_body_length"),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="ck_reviews_rating_range"),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["seller_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", name="uq_reviews_one_per_order"),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(
            "ix_reviews_listing_created", ["listing_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_reviews_seller_created", ["seller_id", "created_at"], unique=False
        )

    op.create_table(
        "dispute_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dispute_id", sa.Integer(), nullable=False),
        sa.Column("from_status", sa.String(length=24), nullable=True),
        sa.Column("to_status", sa.String(length=24), nullable=False),
        sa.Column("actor_id", sa.Integer(), nullable=True),
        sa.Column("note", sa.String(length=2000), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "from_status IS NULL OR from_status IN "
            "('OPEN','UNDER_REVIEW','RESOLVED_FOR_BUYER','RESOLVED_FOR_SELLER')",
            name="ck_dispute_history_from_status",
        ),
        sa.CheckConstraint(
            "to_status IN ('OPEN','UNDER_REVIEW','RESOLVED_FOR_BUYER','RESOLVED_FOR_SELLER')",
            name="ck_dispute_history_to_status",
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["dispute_id"], ["disputes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("dispute_history", schema=None) as batch_op:
        batch_op.create_index(
            "ix_dispute_history_dispute_created", ["dispute_id", "created_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dispute_history", schema=None) as batch_op:
        batch_op.drop_index("ix_dispute_history_dispute_created")

    op.drop_table("dispute_history")
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index("ix_reviews_seller_created")
        batch_op.drop_index("ix_reviews_listing_created")

    op.drop_table("reviews")
    with op.batch_alter_table("disputes", schema=None) as batch_op:
        batch_op.drop_index("ix_disputes_status_opened")

    op.drop_table("disputes")
    # ### end Alembic commands ###
