"""persist OTP IP request quota

Revision ID: f6495a62d8ec
Revises: 3d5f4d1f075b
Create Date: 2026-10-04 02:48:42.154761

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f6495a62d8ec"
down_revision = "3d5f4d1f075b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "otp_request_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("request_ip", sa.String(length=45), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("otp_request_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_otp_request_events_occurred_at"), ["occurred_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_otp_request_events_request_ip"), ["request_ip"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("otp_request_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_otp_request_events_request_ip"))
        batch_op.drop_index(batch_op.f("ix_otp_request_events_occurred_at"))

    op.drop_table("otp_request_events")
    # ### end Alembic commands ###
